name: Cargo Publish

on:
  push:
    branches: master
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@v4
    - name: login
      run: cargo login ${{ secrets.CARGO_SECRET }}
    - name: Publish
      run: cargo publish --no-verify
