name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@v4
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.12
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2.6.2
    - name: Decrypt meshes
      shell: bash
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      run: |
        for FILE in collision_meshes/**/*.gpg; do
          gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output "${FILE%.gpg}" "$FILE"
        done
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
